config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "parties#index"
  resources :parties do
    resources :guests
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :party
  # validates :name, presence: true
  # validates :email, presence: true
  # validates :phone_no, presence: true ,length: { minimum: 10 }
end

app/models/party.rb
class Party < ApplicationRecord
    has_many :guests
  validates :party_name, presence: true
  validates :date_time, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def create
    @party = Party.find(params[:party_id])
    @guest = @party.guests.create(guest_params)
    redirect_to party_path(@party)
  end

  def destroy
    @party = Party.find(params[:party_id])
    @guest = @party.guests.find(params[:id])
    @guest.destroy
     redirect_to party_path(@party)
  end

  private
    def guest_params
      params.require(:guest).permit(:name, :email, :phone_no)
    end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  def index
    @parties=Party.all
  end
  def show
    @party = Party.find(params[:id])
  end
   def new
    @party = Party.new
  end

  def create
    @party = Party.new(party_params)

    if @party.save
      redirect_to @party
    else
      render :new, status: :unprocessable_entity
    end
  end
  private
    def party_params
      params.require(:party).permit(:party_name, :date_time, :notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/guests/index.html.erb
<h1>Guests#index</h1>
<p>Find me in app/views/guests/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Event Aangement" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Event Aangement">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parties/index.html.erb
<h1>Event Management</h1>

<ul>
  <% @parties.each do |party| %>
    <li>
        <%= link_to party.party_name, party %>    
    </li>
  <% end %>
</ul>

<%= link_to "New Party", new_party_path %>

app/views/parties/new.html.erb
<h1>New Party</h1>

<%= form_with model: @party do |form| %>
  <div>
    <%= form.label :party_name %><br>
    <%= form.text_field :party_name %>
    <div>
        <% @party.errors.full_messages_for(:party_name).each do |message| %>
      <div><%= message %></div>
      <% end %>
     </div>
  </div>

<div>
  <%= form.label :date_time %><br>
  <%= form.text_field :date_time %>
  <div>
    <% @party.errors.full_messages_for(:date_time).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
</div>

  <div>
    <%= form.label :notes %><br>
    <%= form.text_area :notes %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<div>
<%=link_to "Back",root_path%>
</div>

app/views/parties/show.html.erb
<h1><%= @party.party_name %></h1>
<p>
<p>Event date and time :<%=@party.date_time %></p>
</p>
<p>Description/notes :<%= @party.notes %></p>

<div>
<h2>List of Guests to participate</h2>
<% @party.guests.each do |guest| %>
  <p>
    <strong>Guest Name:</strong>
    <%= guest.name %>
<%= link_to "Remove",
            party_guest_path(@party, guest),
            data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
            } %>
  </p>
  
  <p>
    <strong>email-id:</strong>
    <%= guest.email %>
  </p>
    <p>
    <strong>phone number:</strong>
    <%= guest.phone_no %>
  </p>

<% end %>
</div>

<h2>Add people:</h2>
<%= form_with model: [ @party, @party.guests.build ] do |form| %>
  <p>
    <%= form.label :full_name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :email_id %><br>
    <%= form.text_field :email %>
  </p>
    <p>
    <%= form.label :phonenumber %><br>
    <%= form.text_field :phone_no %>
  </p>
  <p>
    <%= form.submit %>
  </p>

<% end %>

<div>
<%=link_to "Back",root_path%>
</div>